In [8]:
import numpy as np  
import pandas as pd 
import matplotlib.pyplot as plt

# Data set file N1

In [3]:
d_Cab = pd.read_csv('../input/data-set-week-2/Cab_Data.csv')
d_Cab.head(3)

In [10]:
d_Cab.rename(columns ={'Transaction ID': 'Transaction_ID', 'Date of Travel': 'Date_of_Travel', 'KM Travelled': 'KM_Travelled', 'Price Charged': 'Price_Charged', 'Cost of Trip': 'Cost_of_Trip' }, inplace = True)
d_Cab.columns

**H1: Price charged per KM travelled**

In [13]:
# plot our data
plt.xlabel('KM Travelled')
plt.ylabel('Price charged')
plt.scatter( d_Cab.KM_Travelled,d_Cab.Price_Charged, marker="*", color= "blue")

**H2: the Cost of the Trip depends on the company**

In [16]:
# plot our data
plt.xlabel('Company')
plt.ylabel('Cost_of_Trip')
plt.scatter( d_Cab.Company,d_Cab.Cost_of_Trip, marker="*", color= "red")

# Data set file N2

In [15]:
d_City = pd.read_csv('../input/data-set-week-2/City.csv')
d_City.head(3)

**H3: nb of population varies from a city to another**

In [21]:
plt.figure(figsize=(20,8))
plt.ylabel('City')
plt.xlabel('Population')
plt.scatter( d_City.Population,d_City.City, marker="+", color= "green")

**H4: nb  of users depends on the nb of population**

In [39]:
plt.figure(figsize=(20,8))
plt.xlabel('users')
plt.ylabel('Population')
plt.scatter( d_City.Users,d_City.Population, marker="+", color= "brown")

# Data set file N3

In [26]:
import pandas as pd
d_Customer = pd.read_csv('../input/data-set-week-2/Customer_ID.csv')
d_Customer.head(3)

In [27]:
d_Customer.rename(columns ={'Customer ID': 'Customer_ID', 'Income (USD/Month)': 'Income'}, inplace = True)
d_Customer.columns

**H5: men and women are similar in income**

In [30]:
plt.figure(figsize=(20,8))
plt.xlabel('Gender')
plt.ylabel('Income (USD/Month)')
plt.scatter( d_Customer.Gender,d_Customer.Income, marker="+", color= "yellow")

**H6 : the age can affect the income**

In [37]:
plt.figure(figsize=(20,8))
plt.xlabel('Income (USD/Month)')
plt.ylabel('Age')
plt.scatter ( d_Customer.Income, d_Customer.Age, marker="+", color= "pink")